# preload = /home/rodrigo/.config/wallpapers/arch-catppuccin.jpg
# wallpaper = , /home/rodrigo/.config/wallpapers/arch-catppuccin.jpg
wallpaper {
    monitor = DVI-I-2
    path = /home/rodrigo/.config/wallpapers/arch-catppuccin.jpg
    fit_mode = cover
}
